version = 0.1

[default.deploy.parameters]
stack_name = "chat-bot-application-npl"
resolve_s3 = true
s3_prefix = "chat-bot-application-npl"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
